model:
  nt: 20
  nb_of_layers: 4
  type_of_all_layers: [ConvLSTM, ConvLSTM, ConvLSTM, TAAConvLSTM]
  input_shape: [2, 128, 128] # n_channels, im_hegiht, im_width
  stack_sizes: [48, 96, 192] # same as R_stack_sizes
  A_filt_sizes: [3, 3, 3]
  Ahat_filt_sizes: [3, 3, 3, 3]
  R_filt_sizes: [3, 3, 3, 3]
  attention_horizon: 4
  Nh: 4
  key_query_dimension: 250
  value_dimension: 250

training:
  dataset_path: "../../DATASETS/KITTI/DST_EV/" #Modify this
  model_name: PredNet_with_TAAConvLSTM_Kitti
  save_model: True
  nb_epochs: 100
  batch_size: 1
  samples_per_epoch: 500
  N_seq_val: 100
