model:
  nt: 20
  nb_of_layers: 4
  type_of_all_layers: [ConvLSTM, ConvLSTM, ConvLSTM, TAAConvLSTM]
  input_shape: [2, 128, 128] # n_channels, im_hegiht, im_width
  stack_sizes: [48, 96, 192] # same as R_stack_sizes
  A_filt_sizes: [3, 3, 3]
  Ahat_filt_sizes: [3, 3, 3, 3]
  R_filt_sizes: [3, 3, 3, 3]
  attention_horizon: 4 #attention horizon
  Nh: 4 # number of heads
  key_query_dimension: 250 #dimensions of key and query as defined by Bello et al.
  value_dimension: 250

training:
  dataset_path: "../DATASETS/KITTI/DST_EV/"
  model_name: V3_4layers_ATT4_4heads_250_250_BEST
  save_model: True
  nb_epochs: 100
  batch_size: 4
  samples_per_epoch: 500
  N_seq_val: 100
  optimizer:
    type: Adam
    initial_lr: 0.1
    lr_scheduling: cosine_decay
